RIGHT_PANEL_X = 700
ACTION_BUTTON_WIDTH = 200
ACTION_BUTTON_HEIGHT = 40
ACTION_BUTTON_GAP = 5
RIGHT_PANEL_START_Y = 25


def right_action_button(index: int):
    return (
        (RIGHT_PANEL_X, RIGHT_PANEL_START_Y + index * (ACTION_BUTTON_HEIGHT + ACTION_BUTTON_GAP)),
        (ACTION_BUTTON_WIDTH, ACTION_BUTTON_HEIGHT),
    )
