courses:
- 1ma1df01
- 2ma2dfb01
rg_class:
courses_path: .
config_path: .
exam_path: .
comments_path: comments_GUI.txt
report_student_path: report_outline_student.tex
report_skeleton_path: report_skeleton.tex
